name: Publish to gh-pages

on:
  repository_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    - name: Use Nide.js
    with:
      node-version: '10.13.0'
    - run: npm install
    - run: npm start